name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: run_action
      with:
        key: "keyB"
        map: |
          {
            "keyA": {
              "env1A": "value1A",
              "env2A": "value2A",
              "env3A": "value3A"
            },
            ".*": {
              "env1B": "value1B",
              "env2B": "value2B",
              "env3B": "value3B"
            }
          }
    - name: 'Test Actions Parameters'
      run: |
        test "${{env.env1B}}" = "value1B"
        test "${{env.env2B}}" = "value2B"
        test "${{env.env3B}}" = "value3B"
        test "${{steps.run_action.outputs.env1B}}" = "value1B"
        test "${{steps.run_action.outputs.env2B}}" = "value2B"
        test "${{steps.run_action.outputs.env3B}}" = "value3B"
